// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace CoreBridge
{
    public unsafe partial class Core
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity, DllImport("sourcesharp.dll", EntryPoint = "RegServerCommand", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void RegServerCommand([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CppSharp.Runtime.UTF8Marshaller))] string command);

            [SuppressUnmanagedCodeSecurity, DllImport("sourcesharp.dll", EntryPoint = "RegClientCommand", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void RegClientCommand([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(CppSharp.Runtime.UTF8Marshaller))] string command);
        }

        public static void RegServerCommand(string command)
        {
            __Internal.RegServerCommand(command);
        }

        public static void RegClientCommand(string command)
        {
            __Internal.RegClientCommand(command);
        }
    }
}
